name: practice
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  flutter_hooks: ^0.20.4
  smooth_page_indicator: ^1.1.0
  go_router: ^13.1.0
  cached_network_image: ^3.3.1
  flash: ^3.1.0
  flutter_local_notifications: ^16.3.2
  dio: ^5.4.0
  dartz: ^0.10.1
  google_fonts: ^6.1.0
  get_it: ^7.6.7
  firebase_core: ^2.25.3
  firebase_messaging: ^14.7.14
  url_launcher: ^6.2.4
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  flutter_svg: ^2.0.9
  image_picker: ^1.0.7
  font_awesome_flutter: ^10.7.0
  hexagon: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svgs/
