// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnSK4k5xz-sfRR7hnhLJ1icu43Z-rRjuY',
    appId: '1:494563465828:web:186ff12a3123a1fad7dd71',
    messagingSenderId: '494563465828',
    projectId: 'just-a-lil-login-page',
    authDomain: 'just-a-lil-login-page.firebaseapp.com',
    storageBucket: 'just-a-lil-login-page.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIsC-M3gu5lR1algr-ebfvITQEjYhLTx8',
    appId: '1:494563465828:android:c712a1b13fb8427fd7dd71',
    messagingSenderId: '494563465828',
    projectId: 'just-a-lil-login-page',
    storageBucket: 'just-a-lil-login-page.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASYGRtc3dayoOkfuINmT8L9MV4QD9P7Uk',
    appId: '1:494563465828:ios:53b9e446fdf99738d7dd71',
    messagingSenderId: '494563465828',
    projectId: 'just-a-lil-login-page',
    storageBucket: 'just-a-lil-login-page.appspot.com',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASYGRtc3dayoOkfuINmT8L9MV4QD9P7Uk',
    appId: '1:494563465828:ios:f3dcc5631b1a84e4d7dd71',
    messagingSenderId: '494563465828',
    projectId: 'just-a-lil-login-page',
    storageBucket: 'just-a-lil-login-page.appspot.com',
    iosBundleId: 'com.example.loginPage.RunnerTests',
  );
}
